### ISSUE TITLE
Support for arm64 platform.

### ISSUE THREAD

**Issue by odidev** [instana/robot-shop#139]
I have been working on deploying the instana/robot-shop on the ARM64 platform using the docker-compose method. But the project does not work on the arm64 platform. I have made some changes in some files to get this work on the arm64 platform. With these changes, it works fine on the x64 and Arm64 platforms. Please share your suggestions on the same. 

**Commit Link: -** https://github.com/odidev/robot-shop/commit/4776c88a670e7ef0c751d0c02024b6577fd9a6db

**Comment by odidev** [comment]
Hi Team,

Adding a gentle reminder to take a look at the above changes.

**Comment by kshpdr** [comment]
Hi. Tried on my Mac M1 Pro, still doesn't work. 

OS: macOS Monterey, 12.5

Erorrs:

robot-shop-dispatch-1:
`2023-05-10 20:47:03 2023/05/10 18:47:03 instana: INFO: failed to send a request to http://localhost:42699/: Get "http://localhost:42699/": dial tcp 127.0.0.1:42699: connect: connection refused
2023-05-10 20:47:03 2023/05/10 18:47:03 instana: INFO: failed to send a request to http://172.19.0.1:42699/: Get "http://172.19.0.1:42699/": dial tcp 172.19.0.1:42699: connect: connection refu`

robot-shop-catalogue-1 and robot-shop-user-1:
`{"level":"error","time":1683744492911,"pid":1,"hostname":"e53ad4a19df9","msg":"ERROR {\"name\":\"MongoNetworkError\"}","v":1}` 

robot-shop-shipping-1:
`2023-05-10 20:48:56 The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
2023-05-10 20:48:56     at sun.reflect.GeneratedConstructorAccessor31.newInstance(Unknown Source) ~[na:na]
2023-05-10 20:48:56     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_302]
2023-05-10 20:48:56     at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_302]
2023-05-10 20:48:56     at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
2023-05-10 20:48:56     at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
2023-05-10 20:48:56     at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
2023-05-10 20:48:56     at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
2023-05-10 20:48:56     at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
2023-05-10 20:48:56     at com.mysql.cj.NativeSession.connect(NativeSession.java:144) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
2023-05-10 20:48:56     at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:850) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
2023-05-10 20:48:56     ... 73 common frames omitted
2023-05-10 20:48:56 Caused by: java.net.ConnectException: Connection refused (Connection refused)
2023-05-10 20:48:56     at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_302]
2023-05-10 20:48:56     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_302]
2023-05-10 20:48:56     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_302]
2023-05-10 20:48:56     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_302]
2023-05-10 20:48:56     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_302]
2023-05-10 20:48:56     at java.net.Socket.connect(Socket.java:607) ~[na:1.8.0_302]
2023-05-10 20:48:56     at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
2023-05-10 20:48:56     at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
2023-05-10 20:48:56     ... 75 common frames omitted`

**Comment by odidev** [comment]
Hi @steveww 

Adding a gentle reminder to take a look at the above [changes](https://github.com/instana/robot-shop/issues/139#issue-1621192193).

**Comment by odidev** [comment]
Hi @steveww 

If the above changes look good I will raise the PR.
