### ISSUE TITLE
JSONDecodeError while load gen with locust

### ISSUE THREAD

**Issue by Angi2412** [instana/robot-shop#55]
Hello,

now that I have successfully deployed the robot-shop to my local Kubernetes cluster, I get some error messages during the load generation with locust. 

Sometimes when it tries to get the area code with the line:
`code = choice(self.client.get('/api/shipping/codes, headers={'x-forwarded-for': fake_ip}).json())`
It raises an `JSONDecode` error, which tells me that it probably did not get the expected response from the api.
It also seems that this is unattached to what IP is used.

here is the full error message:
```
ERROR:locust.user.task:Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\y509019\OneDrive - Software AG\Documents\Projekte\Thesis\venv\lib\site-packages\locust\user\task.py", line 290, in run
    self.execute_next_task()
  File "C:\Users\y509019\OneDrive - Software AG\Documents\Projekte\Thesis\venv\lib\site-packages\locust\user\task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "C:\Users\y509019\OneDrive - Software AG\Documents\Projekte\Thesis\venv\lib\site-packages\locust\user\task.py", line 428, in execute_task
    task(self.user)
  File "C:\Users\y509019\OneDrive - Software AG\Documents\Projekte\Thesis\data\loadtest\robotshop.py", line 78, in load
    code = choice(self.client.get('/api/shipping/codes', headers={'x-forwarded-for': fake_ip}).json())
  File "C:\Users\y509019\OneDrive - Software AG\Documents\Projekte\Thesis\venv\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2032.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2032.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2032.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Angi2412** [comment]
It looks like the error codes with which the API responds when the requests fail are `0` and `503`.
`503`: google says it means "service is unavailable": Does that mean that the pod is overloaded and can therefore not respond?
And for the status code `0`, I found no explanation.

**Comment by steveww** [comment]
I think you just answered your own question.
This does not happen on my system, could be a resource limitation.

**Comment by cedricziel** [comment]
side-note: K8s has strong guarantees about resources. If you were to give the node more headroom (CPU & RAM), you could fix it on your end and scheduling could happen.

**Comment by Angi2412** [comment]
Thanks! I am using the application for test data generation for an autoscaling approach using machine learning. Because I am varying the resource limits and load on the application, it could be possible that it caused this behaviour. But still, the outcoming data makes not that much sense. With constant CPU and memory limit and an increasing number of pods, the response time seems not to decrease linearly (independent from the microservice).

**Comment by steveww** [comment]
That is what I would expect. The micro services are not doing any heavy compute work, giving each service more CPU will not make them run faster. You could add your own service that does some heavy maths, this would scale out better with more resources.
